# Copyright (c) 2026 K.N.Narin (github.com/narin-kura). All rights reserved.
# Non-commercial use only. Commercial use requires written permission: github.com/narin-kura
# See LICENSE for full terms.
"""Rule-based "Recommend My Stack" engine.

Given a short questionnaire (project type, scale, cloud preference, cost vs.
performance priority, database needs, AI needs, security level, and any
components the user already wants to use), picks a cost-optimized and secure
starter stack from the ArchLens service catalog (see web/static/index.html
SERVICES), grouped by architectural role.

If GEMINI_API_KEY or ANTHROPIC_API_KEY is configured, a short written
rationale is additionally generated by an LLM on top of the rule-based
picks (mirrors archlens.parsers.text.TextParser's provider fallback).
"""

from __future__ import annotations
import json
import logging
import os
from typing import Optional, Tuple

logger = logging.getLogger(__name__)

# Each entry: (id, name, service, type, provider) — must match an id in
# web/static/index.html's SERVICES array so the frontend can look up the
# full catalog entry (icon, cat, ...) by id.
Entry = Tuple[str, str, str, str, str]

ROLE_CATALOG: dict[str, dict[str, Entry]] = {
    "compute_serverless": {
        "aws": ("aws_lambda", "Lambda", "lambda", "SERVERLESS", "aws"),
        "gcp": ("gcp_cloudrun", "Cloud Run", "cloud_run", "SERVERLESS", "gcp"),
        "azure": ("az_functions", "Functions", "azure_functions", "SERVERLESS", "azure"),
    },
    "compute_container": {
        "aws": ("aws_fargate", "Fargate", "fargate", "CONTAINER", "aws"),
        "gcp": ("gcp_gke", "GKE", "gke", "CONTAINER", "gcp"),
        "azure": ("az_containerapps", "Container Apps", "container_apps", "CONTAINER", "azure"),
        "generic": ("t_k8s", "Kubernetes", "kubernetes", "CONTAINER", "generic"),
    },
    "db_relational": {
        "aws": ("aws_rds", "RDS", "rds", "DATABASE", "aws"),
        "gcp": ("gcp_cloudsql", "Cloud SQL", "cloud_sql", "DATABASE", "gcp"),
        "azure": ("az_sql", "Azure SQL", "azure_sql", "DATABASE", "azure"),
        "generic": ("d_postgres", "PostgreSQL", "postgresql", "DATABASE", "generic"),
    },
    "db_scale": {
        "aws": ("aws_aurora", "Aurora", "aurora", "DATABASE", "aws"),
        "gcp": ("gcp_spanner", "Spanner", "spanner", "DATABASE", "gcp"),
        "azure": ("az_cosmos", "Cosmos DB", "cosmos_db", "DATABASE", "azure"),
        "generic": ("d_cassandra", "Cassandra", "cassandra", "DATABASE", "generic"),
    },
    "db_nosql": {
        "aws": ("aws_dynamodb", "DynamoDB", "dynamodb", "DATABASE", "aws"),
        "gcp": ("gcp_firestore", "Firestore", "firestore", "DATABASE", "gcp"),
        "azure": ("az_cosmos", "Cosmos DB", "cosmos_db", "DATABASE", "azure"),
        "generic": ("d_mongodb", "MongoDB", "mongodb", "DATABASE", "generic"),
    },
    "db_analytics": {
        "aws": ("aws_redshift", "Redshift", "redshift", "DATABASE", "aws"),
        "gcp": ("gcp_bigquery", "BigQuery", "bigquery", "DATABASE", "gcp"),
        "azure": ("az_synapse", "Synapse", "synapse", "DATABASE", "azure"),
        "generic": ("d_clickhouse", "ClickHouse", "clickhouse", "DATABASE", "generic"),
    },
    "storage": {
        "aws": ("aws_s3", "S3", "s3", "STORAGE", "aws"),
        "gcp": ("gcp_gcs", "Cloud Storage", "gcs_bucket", "STORAGE", "gcp"),
        "azure": ("az_blob", "Blob Storage", "blob_storage", "STORAGE", "azure"),
    },
    "cache": {
        "aws": ("aws_elasticache", "ElastiCache", "elasticache", "CACHE", "aws"),
        "gcp": ("gcp_memstore", "Memorystore", "memorystore", "CACHE", "gcp"),
        "azure": ("az_redis", "Cache (Redis)", "azure_redis", "CACHE", "azure"),
        "generic": ("t_redis", "Redis", "redis", "CACHE", "generic"),
    },
    "cdn": {
        "aws": ("aws_cloudfront", "CloudFront", "cloudfront", "CDN", "aws"),
        "gcp": ("gcp_cdn", "Cloud CDN", "cloud_cdn", "CDN", "gcp"),
        "azure": ("az_frontdoor", "Front Door", "front_door", "CDN", "azure"),
        "generic": ("s_cloudflare", "Cloudflare", "cloudflare", "CDN", "generic"),
    },
    "gateway": {
        "aws": ("aws_apigw", "API Gateway", "apigateway", "GATEWAY", "aws"),
        "gcp": ("gcp_lb", "Cloud LB", "cloud_lb", "GATEWAY", "gcp"),
        "azure": ("az_apim", "API Mgmt", "apim", "GATEWAY", "azure"),
        "generic": ("t_nginx", "Nginx", "nginx", "GATEWAY", "generic"),
    },
    "queue": {
        "aws": ("aws_sqs", "SQS", "sqs", "QUEUE", "aws"),
        "gcp": ("gcp_pubsub", "Pub/Sub", "pubsub", "QUEUE", "gcp"),
        "azure": ("az_servicebus", "Service Bus", "service_bus", "QUEUE", "azure"),
        "generic": ("d_kafka", "Kafka", "kafka", "QUEUE", "generic"),
    },
    "network": {
        "aws": ("aws_vpc", "VPC", "vpc", "NETWORK", "aws"),
        "gcp": ("gcp_vpc", "VPC Network", "gcp_vpc", "NETWORK", "gcp"),
        "azure": ("az_bastion", "Bastion", "azure_bastion", "NETWORK", "azure"),
    },
    "iam": {
        "aws": ("aws_iam", "IAM", "iam_role", "IAM", "aws"),
        "azure": ("az_iam", "Azure AD", "azure_ad", "IAM", "azure"),
        "generic": ("s_keycloak", "Keycloak", "keycloak", "IAM", "generic"),
    },
    "secrets": {
        "aws": ("aws_secrets", "Secrets Mgr", "secrets_manager", "IAM", "aws"),
        "gcp": ("gcp_secrets", "Secret Manager", "secret_manager", "IAM", "gcp"),
        "azure": ("az_keyvault", "Key Vault", "key_vault", "IAM", "azure"),
        "generic": ("s_vault", "Vault", "vault", "IAM", "generic"),
    },
    "monitoring": {
        "aws": ("aws_cloudwatch", "CloudWatch", "cloudwatch", "MONITORING", "aws"),
        "gcp": ("gcp_monitor", "Cloud Monitor", "cloud_monitoring", "MONITORING", "gcp"),
        "azure": ("az_monitor", "Azure Monitor", "azure_monitor", "MONITORING", "azure"),
        "generic": ("m_grafana", "Grafana", "grafana", "MONITORING", "generic"),
    },
    "audit": {
        "aws": ("aws_cloudtrail", "CloudTrail", "cloudtrail", "MONITORING", "aws"),
        "azure": ("az_sentinel", "Sentinel", "sentinel", "MONITORING", "azure"),
        "generic": ("s_falco", "Falco", "falco", "MONITORING", "generic"),
    },
    "cspm": {
        "aws": ("aws_guardduty", "GuardDuty", "guardduty", "MONITORING", "aws"),
        "azure": ("az_sentinel", "Sentinel", "sentinel", "MONITORING", "azure"),
        "generic": ("s_wiz", "Wiz", "wiz", "MONITORING", "generic"),
    },
    "waf": {
        "aws": ("s_waf", "AWS WAF", "waf", "NETWORK", "aws"),
        "gcp": ("gcp_armor", "Cloud Armor", "cloud_armor", "NETWORK", "gcp"),
        "generic": ("s_cloudflare", "Cloudflare", "cloudflare", "CDN", "generic"),
    },
    "vuln_scan": {
        "generic": ("s_trivy", "Trivy", "trivy", "MONITORING", "generic"),
    },
    "cicd": {
        "generic": ("t_gha", "GitHub Actions", "github_actions", "OTHER", "generic"),
    },
    "gitops": {
        "generic": ("t_argocd", "Argo CD", "argocd", "OTHER", "generic"),
    },
    "iac": {
        "generic": ("t_terraform", "Terraform", "terraform", "OTHER", "generic"),
    },
    "llm_gateway": {
        "aws": ("aws_bedrock", "Bedrock", "bedrock", "GATEWAY", "aws"),
        "gcp": ("gcp_vertexai", "Vertex AI", "vertex_ai", "COMPUTE", "gcp"),
        "azure": ("az_openai", "Azure OpenAI", "azure_openai", "GATEWAY", "azure"),
        "generic": ("ai_anthropic", "Anthropic API", "anthropic_api", "GATEWAY", "generic"),
    },
    "vector_db": {
        "pgvector": ("ai_pgvector", "pgvector", "pgvector", "DATABASE", "generic"),
        "managed": ("ai_pinecone", "Pinecone", "pinecone", "DATABASE", "generic"),
    },
    "llm_framework": {
        "generic": ("ai_langchain", "LangChain", "langchain", "OTHER", "generic"),
    },
    "ml_training": {
        "aws": ("aws_sagemaker", "SageMaker", "sagemaker", "COMPUTE", "aws"),
        "gcp": ("gcp_vertexai", "Vertex AI", "vertex_ai", "COMPUTE", "gcp"),
        "azure": ("az_ml", "Azure ML", "azure_ml", "COMPUTE", "azure"),
        "generic": ("ai_ray", "Ray", "ray", "COMPUTE", "generic"),
    },
    "gpu_compute": {
        "aws": ("aws_gpu", "EC2 GPU (P5/P4)", "ec2_gpu", "COMPUTE", "aws"),
        "gcp": ("gcp_gpu", "GPU VM (A3/A2)", "gcp_gpu_vm", "COMPUTE", "gcp"),
        "azure": ("az_gpu", "GPU VM (ND/NC)", "azure_gpu_vm", "COMPUTE", "azure"),
        "generic": ("nv_runpod", "RunPod", "runpod", "COMPUTE", "generic"),
    },
    "llm_serving": {
        "generic": ("nv_vllm", "vLLM", "vllm", "COMPUTE", "generic"),
    },
    "iot_gateway": {
        "aws": ("aws_iotcore", "IoT Core", "iot_core", "GATEWAY", "aws"),
        "azure": ("az_iothub", "IoT Hub", "iot_hub", "GATEWAY", "azure"),
        "generic": ("hw_mqtt", "MQTT Broker", "mqtt_broker", "QUEUE", "generic"),
    },
    "edge_compute": {
        "aws": ("aws_greengrass", "IoT Greengrass", "iot_greengrass", "COMPUTE", "aws"),
        "azure": ("az_iotedge", "IoT Edge", "iot_edge", "COMPUTE", "azure"),
        "generic": ("hw_fpga", "FPGA Instance", "fpga", "COMPUTE", "generic"),
    },
}

# Human-readable reason shown next to each recommended component.
ROLE_WHY: dict[str, str] = {
    "compute_serverless": "Serverless compute scales to zero, so a low-traffic app costs almost nothing when idle.",
    "compute_container": "Containers give you portable, horizontally-scalable compute as traffic grows.",
    "db_relational": "Managed relational database for your core application data, with automated backups and patching.",
    "db_scale": "A horizontally-scalable database that keeps up with high read/write volume at enterprise scale.",
    "db_nosql": "A managed NoSQL store for flexible, high-throughput document/key-value data.",
    "db_analytics": "A columnar warehouse built for fast analytical queries over large datasets.",
    "storage": "Object storage for files, backups, and static assets — pay only for what you store, with lifecycle policies to cut cost.",
    "cache": "An in-memory cache reduces database load and latency for frequently-read data.",
    "cdn": "A CDN caches content at the edge, cutting origin load and improving global latency.",
    "gateway": "A managed gateway handles routing, throttling, and TLS termination for your endpoints.",
    "queue": "A message queue decouples services for resilient, asynchronous processing.",
    "network": "A private network isolates your resources from the public internet.",
    "iam": "Centralized identity and access management enforces least-privilege access.",
    "secrets": "A secrets manager keeps API keys and credentials out of code and config files.",
    "monitoring": "Centralized monitoring and alerting gives you visibility into performance and incidents.",
    "audit": "Audit logging records who did what — essential for investigations and compliance.",
    "cspm": "Cloud security posture management continuously scans for misconfigurations.",
    "waf": "A web application firewall blocks common attacks (SQLi, XSS) before they reach your app.",
    "vuln_scan": "Container/dependency scanning catches known vulnerabilities before deployment.",
    "cicd": "An automated CI/CD pipeline gives you consistent, repeatable deployments.",
    "gitops": "GitOps continuous delivery keeps your cluster in sync with Git, with easy rollbacks.",
    "iac": "Infrastructure as code makes your environment reproducible, reviewable, and auditable.",
    "llm_gateway": "A managed LLM gateway gives you access to foundation models with built-in scaling and governance.",
    "vector_db": "A vector database stores embeddings for retrieval-augmented generation (RAG).",
    "llm_framework": "An orchestration framework for chaining prompts, tools, and retrieval steps.",
    "ml_training": "A managed ML platform for training and deploying custom models.",
    "gpu_compute": "GPU instances for model training/inference workloads.",
    "llm_serving": "A high-throughput inference server for self-hosted LLMs.",
    "iot_gateway": "An IoT gateway securely ingests telemetry from devices at scale.",
    "edge_compute": "An edge runtime lets devices run logic locally, reducing bandwidth and latency.",
    "your_pick": "You selected this component.",
}

_PROJECT_TYPES = {"web_api", "microservices", "data_pipeline", "ai_llm", "mobile_backend", "iot_embedded"}
_SCALES = {"startup", "growth", "enterprise"}
_CLOUDS = {"aws", "gcp", "azure", "generic"}
_PRIORITIES = {"cost", "balanced", "performance"}
_DATABASES = {"relational", "nosql", "analytics", "none"}
_AI_NEEDS = {"none", "llm_api", "custom_ml", "gpu_inference"}
_SECURITY_LEVELS = {"basic", "standard", "high"}


def _service_to_roles() -> dict[str, set[str]]:
    mapping: dict[str, set[str]] = {}
    for role, by_key in ROLE_CATALOG.items():
        for entry in by_key.values():
            mapping.setdefault(entry[2], set()).add(role)
    return mapping


_SERVICE_TO_ROLES = _service_to_roles()


def _role_family(role: str) -> str:
    """Group roles that are alternative tiers of the same thing.

    A must-have that satisfies e.g. db_relational should also suppress
    db_scale/db_nosql/db_analytics — the user already picked a database,
    we shouldn't suggest a second one in a different tier.
    """
    for prefix in ("db_", "compute_"):
        if role.startswith(prefix):
            return prefix[:-1]
    return role


def _resolve(role: str, cloud_key: str, database: str) -> Optional[Entry]:
    if role == "vector_db":
        key = "pgvector" if database == "relational" else "managed"
        return ROLE_CATALOG["vector_db"][key]
    by_cloud = ROLE_CATALOG.get(role)
    if not by_cloud:
        return None
    return (
        by_cloud.get(cloud_key)
        or by_cloud.get("generic")
        or by_cloud.get("aws")
        or next(iter(by_cloud.values()))
    )


def recommend(req: dict) -> dict:
    """Recommend a cost-optimized, secure stack from the catalog."""
    project_type = req.get("project_type") if req.get("project_type") in _PROJECT_TYPES else "web_api"
    scale = req.get("scale") if req.get("scale") in _SCALES else "startup"
    cloud = req.get("cloud") if req.get("cloud") in _CLOUDS else "generic"
    priority = req.get("priority") if req.get("priority") in _PRIORITIES else "balanced"
    database = req.get("database") if req.get("database") in _DATABASES else "relational"
    ai_needs = req.get("ai_needs") if req.get("ai_needs") in _AI_NEEDS else "none"
    security_level = req.get("security_level") if req.get("security_level") in _SECURITY_LEVELS else "standard"
    realtime = bool(req.get("realtime"))
    must_haves = req.get("must_haves") or []

    cloud_key = cloud if cloud in ("aws", "gcp", "azure") else "generic"

    recommended: list[dict] = []
    added_ids: set[str] = set()
    filled_families: set[str] = set()

    def add(role: str, entry: Entry, why: str) -> None:
        cid, name, service, ctype, provider = entry
        if cid in added_ids:
            for item in recommended:
                if item["id"] == cid and why not in item["why"]:
                    item["why"] = item["why"] + " " + why
                    break
            return
        added_ids.add(cid)
        recommended.append({
            "id": cid, "name": name, "provider": provider,
            "type": ctype, "service": service, "role": role, "why": why,
        })

    # 1. Components the user already wants — keep them, and skip suggesting
    #    a different option for the same role.
    for mh in must_haves:
        mh_id = mh.get("id")
        mh_service = mh.get("service", "")
        if not mh_id or mh_id in added_ids:
            continue
        added_ids.add(mh_id)
        recommended.append({
            "id": mh_id,
            "name": mh.get("name", mh_id),
            "provider": mh.get("provider", "generic"),
            "type": mh.get("type", "OTHER"),
            "service": mh_service,
            "role": "your_pick",
            "why": ROLE_WHY["your_pick"],
        })
        filled_families |= {_role_family(r) for r in _SERVICE_TO_ROLES.get(mh_service, set())}

    # 2. Decide which roles this stack needs.
    roles: list[str] = []

    if project_type == "iot_embedded":
        roles += ["iot_gateway", "edge_compute"]
    else:
        roles.append("compute_serverless" if scale == "startup" else "compute_container")

    if database == "relational":
        roles.append("db_scale" if scale == "enterprise" else "db_relational")
    elif database == "nosql":
        roles.append("db_nosql")
    elif database == "analytics":
        roles.append("db_analytics")

    roles.append("storage")

    if scale != "startup" or realtime or priority == "performance":
        roles.append("cache")

    if project_type in ("web_api", "microservices", "mobile_backend", "ai_llm"):
        roles += ["cdn", "gateway"]

    if realtime or project_type in ("data_pipeline", "microservices"):
        roles.append("queue")

    if security_level in ("standard", "high") or scale != "startup":
        roles.append("network")

    roles += ["iam", "monitoring"]

    if security_level in ("standard", "high") or ai_needs != "none":
        roles.append("secrets")

    if security_level in ("standard", "high"):
        roles += ["audit", "vuln_scan"]

    if security_level == "high":
        roles += ["cspm", "waf"]

    roles += ["cicd", "iac"]
    if scale in ("growth", "enterprise") and project_type != "iot_embedded":
        roles.append("gitops")

    if ai_needs == "llm_api":
        roles += ["llm_gateway", "llm_framework"]
        if project_type == "ai_llm":
            roles.append("vector_db")
    elif ai_needs == "custom_ml":
        roles.append("ml_training")
    elif ai_needs == "gpu_inference":
        roles += ["gpu_compute", "llm_serving"]

    # 3. Resolve each role to a concrete catalog entry.
    for role in roles:
        if _role_family(role) in filled_families:
            continue
        entry = _resolve(role, cloud_key, database)
        if entry:
            add(role, entry, ROLE_WHY.get(role, ""))

    return {
        "recommended": recommended,
        "cost_tips": _cost_tips(priority, scale, ai_needs),
        "security_tips": _security_tips(security_level, project_type),
        "ai_summary": _ai_summary(req, recommended),
    }


def _cost_tips(priority: str, scale: str, ai_needs: str) -> list[str]:
    tips = [
        "Use serverless/managed services that scale to zero so you only pay for what you use.",
        "Set lifecycle rules on object storage to auto-tier or delete old data after 30-90 days.",
    ]
    if scale == "startup":
        tips.append("Stay on free tiers where possible (Cloudflare, CloudWatch/Cloud Monitoring free tier, smallest DB instance class).")
    if scale == "enterprise":
        tips.append("Once usage patterns stabilize, move steady-state compute and databases to Reserved/Committed-Use pricing for 30-60% savings.")
    if priority == "cost":
        tips.append("Enable autoscaling with a low minimum instance count, and shut down non-prod environments outside business hours.")
    if ai_needs == "gpu_inference":
        tips.append("GPU instances are the biggest line item — use spot/preemptible GPUs for batch jobs and autoscale inference to zero when idle.")
    if ai_needs in ("llm_api", "gpu_inference"):
        tips.append("Cache repeated LLM responses (semantic cache) to cut API/inference costs on duplicate queries.")
    return tips


def _security_tips(security_level: str, project_type: str) -> list[str]:
    tips = [
        "Enforce least-privilege IAM policies — avoid wildcard (*) actions and resources.",
        "Store all credentials and API keys in the secrets manager above; never commit them to source control.",
        "Enable MFA on root/admin accounts and rotate access keys regularly.",
    ]
    if security_level in ("standard", "high"):
        tips.append("Turn on audit logging from day one — it's far cheaper than reconstructing an incident timeline later.")
    if security_level == "high":
        tips.append("Run a CSPM tool continuously and fail CI/CD on critical misconfigurations.")
    if project_type == "ai_llm":
        tips.append("Rate-limit and validate inputs to LLM endpoints to prevent prompt-injection and runaway token costs.")
    if project_type == "iot_embedded":
        tips.append("Use per-device certificates (not shared secrets) for device auth, and keep firmware update channels signed and encrypted.")
    return tips


_SUMMARY_PROMPT = """You are a cloud architecture advisor. A user answered a short questionnaire \
and a rule-based engine picked the stack below. In 3-5 sentences, explain in plain English why \
this stack fits their needs, focusing on cost-optimization and security trade-offs. Do not just \
list the components again — focus on the reasoning. No markdown headers.

Questionnaire answers:
{req}

Recommended components (role: name):
{components}
"""


def _ai_summary(req: dict, recommended: list[dict]) -> Optional[str]:
    gemini_key = os.getenv("GEMINI_API_KEY")
    anthropic_key = os.getenv("ANTHROPIC_API_KEY")
    if not gemini_key and not anthropic_key:
        return None

    components = "\n".join(f"- {r['role']}: {r['name']}" for r in recommended)
    prompt = _SUMMARY_PROMPT.format(req=json.dumps(req), components=components)

    if gemini_key:
        try:
            return _summary_gemini(prompt, gemini_key)
        except Exception:
            logger.exception("Gemini recommendation summary failed")
            if not anthropic_key:
                return None
    try:
        return _summary_anthropic(prompt, anthropic_key)
    except Exception:
        logger.exception("Anthropic recommendation summary failed")
        return None


def _summary_gemini(prompt: str, api_key: str) -> str:
    import google.generativeai as genai

    genai.configure(api_key=api_key, transport="rest")
    model = genai.GenerativeModel("gemini-2.5-flash")
    response = model.generate_content(prompt, request_options={"timeout": 30})
    return response.text.strip()


def _summary_anthropic(prompt: str, api_key: str) -> str:
    import anthropic

    client = anthropic.Anthropic(api_key=api_key, timeout=30.0, max_retries=1)
    message = client.messages.create(
        model="claude-opus-4-8",
        max_tokens=512,
        messages=[{"role": "user", "content": prompt}],
    )
    return message.content[0].text.strip()
